version: '3.8'

services:
  bot:
    image: ghcr.io/crayonlu/wrap-bot:latest
    container_name: wrap-bot
    restart: unless-stopped
    ports:
      - "8080:8080"  # Admin panel
    env_file:
      - .env
    volumes:
      - ./configs:/app/configs
    networks:
      - bot-network
    environment:
      - APP_ENV_FILE=/app/configs/.env

networks:
  bot-network:
    driver: bridge
